# Generated by Django 4.2.6 on 2025-12-28 11:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('en_name', models.CharField(max_length=255, unique=True, verbose_name='English name')),
                ('serial_number', models.CharField(blank=True, default=None, max_length=6, null=True, validators=[django.core.validators.MaxLengthValidator(6), django.core.validators.MinLengthValidator(0)], verbose_name='intercom')),
                ('address', models.CharField(blank=True, default=None, max_length=255)),
                ('landline_phone', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('superior_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('director', models.CharField(blank=True, max_length=60)),
                ('deputy_director1', models.CharField(blank=True, max_length=60)),
                ('deputy_director2', models.CharField(blank=True, max_length=60)),
                ('deputy_director3', models.CharField(blank=True, max_length=60, verbose_name='Chief Secretary')),
                ('superior_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('en_name'), name='unique_en_name_ci'),
        ),
    ]
