# Generated by Django 4.2.6 on 2023-12-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicOrgInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('en_name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('intercom_phone', models.CharField(max_length=6)),
                ('landline_phone', models.CharField(max_length=10)),
                ('director', models.CharField(max_length=10)),
                ('deputy_director1', models.CharField(blank=True, max_length=10, null=True)),
                ('deputy_director2', models.CharField(blank=True, max_length=10, null=True)),
                ('deputy_director3', models.CharField(blank=True, max_length=10, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
        ),
    ]
