# Generated by Django 4.2.6 on 2023-12-16 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('basicorginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.basicorginfo')),
            ],
            bases=('organization.basicorginfo',),
        ),
        migrations.RemoveField(
            model_name='basicorginfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='basicorginfo',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='basicorginfo',
            name='intercom_phone',
        ),
        migrations.RemoveField(
            model_name='basicorginfo',
            name='landline_phone',
        ),
        migrations.RemoveField(
            model_name='basicorginfo',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='basicorginfo',
            name='en_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('basicorginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.basicorginfo')),
                ('address', models.CharField(max_length=255)),
                ('landline_phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('organization.basicorginfo',),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('basicorginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.basicorginfo')),
                ('superior_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('superior_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            bases=('organization.basicorginfo',),
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('basicorginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.basicorginfo')),
                ('superior_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('superior_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            bases=('organization.basicorginfo',),
        ),
        migrations.CreateModel(
            name='CoastPatrolCorps',
            fields=[
                ('basicorginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.basicorginfo')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.branch')),
            ],
            bases=('organization.basicorginfo',),
        ),
        migrations.CreateModel(
            name='PatrolAreaOffice',
            fields=[
                ('basicorginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.basicorginfo')),
                ('number', models.PositiveSmallIntegerField(choices=[(0, 'Headquarters'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Forth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth'), (9, 'Ninth'), (10, 'Tenth'), (11, 'Eleventh'), (12, 'Twelfth'), (13, 'Thirteenth')])),
                ('dispatch_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('administrative_region', models.CharField(blank=True, max_length=5, null=True)),
                ('dispatch_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.administration')),
            ],
            bases=('organization.basicorginfo',),
        ),
        migrations.CreateModel(
            name='InspectionOffice',
            fields=[
                ('basicorginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.basicorginfo')),
                ('address', models.CharField(max_length=255)),
                ('landline_phone', models.CharField(max_length=10)),
                ('intercom_phone', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('superior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.coastpatrolcorps')),
            ],
            bases=('organization.basicorginfo',),
        ),
        migrations.CreateModel(
            name='Brigade',
            fields=[
                ('basicorginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.basicorginfo')),
                ('number', models.PositiveSmallIntegerField(choices=[(0, 'Headquarters'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Forth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth'), (9, 'Ninth'), (10, 'Tenth'), (11, 'Eleventh'), (12, 'Twelfth'), (13, 'Thirteenth')])),
                ('garrison', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.branch')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.administration')),
            ],
            bases=('organization.basicorginfo',),
        ),
        migrations.AddField(
            model_name='branch',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.administration'),
        ),
    ]
