# Generated by Django 4.2.6 on 2025-12-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='en_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='English name'),
        ),
    ]
