# Generated by Django 4.2.6 on 2026-01-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_unit_en_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='landline_phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
