# Generated by Django 4.2.6 on 2023-12-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_branch_address_branch_landline_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicorginfo',
            name='deputy_director3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Chief Secretary'),
        ),
        migrations.AlterField(
            model_name='brigade',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Headquarters'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Forth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth'), (9, 'Ninth'), (10, 'Tenth'), (11, 'Eleventh'), (12, 'Twelfth'), (13, 'Thirteenth')], null=True),
        ),
    ]
