# Generated by Django 4.2.6 on 2023-12-16 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_basicorginfo_deputy_director3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalUnit',
            fields=[
                ('basicorginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.basicorginfo')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.coastpatrolcorps')),
            ],
            bases=('organization.basicorginfo',),
        ),
    ]
