# Generated by Django 4.2.6 on 2023-12-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_internalunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalunit',
            name='serial_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
