# Generated by Django 4.2.6 on 2023-12-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_internalunit_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolStation',
            fields=[
                ('basicorginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='organization.basicorginfo')),
                ('serial_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.internalunit')),
            ],
            bases=('organization.basicorginfo',),
        ),
    ]
