# Generated by Django 4.2.6 on 2023-12-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_patrolstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrolstation',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='patrolstation',
            name='number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Headquarters'), (1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Forth'), (5, 'Fifth'), (6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth'), (9, 'Ninth'), (10, 'Tenth'), (11, 'Eleventh'), (12, 'Twelfth'), (13, 'Thirteenth')], null=True),
        ),
    ]
