# Generated by Django 4.2.6 on 2023-12-18 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_patrolstation_address_patrolstation_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionoffice',
            name='intercom_phone',
        ),
        migrations.RemoveField(
            model_name='internalunit',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='patrolstation',
            name='intercom_phone',
        ),
        migrations.AddField(
            model_name='basicorginfo',
            name='serial_number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='intercom'),
        ),
    ]
