# Generated by Django 4.2.6 on 2023-10-24 13:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_tree', '0002_alter_category_name_alter_subject_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='context',
            field=ckeditor.fields.RichTextField(default=None, null=True),
        ),
    ]
