# Generated by Django 4.2.6 on 2023-10-24 23:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_tree', '0003_subject_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='context',
            field=ckeditor.fields.RichTextField(blank=True, default=None, null=True),
        ),
    ]
