# Generated by Django 4.2.6 on 2023-10-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_tree', '0004_alter_subject_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
