# Generated by Django 4.2.6 on 2026-02-07 11:34

from django.db import migrations, models
import django.db.models.deletion
import ocean_station.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0003_alter_unit_landline_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('en_name', models.CharField(blank=True, max_length=100, null=True)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(choices=[('north', '北部'), ('central', '中部'), ('south', '南部'), ('east', '東部')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('geo_features', models.TextField(blank=True, null=True)),
                ('exhibit_plan', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='organization.unit')),
            ],
        ),
        migrations.CreateModel(
            name='StationAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='ocean_station.station')),
            ],
        ),
        migrations.CreateModel(
            name='StationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('accessible_toilet', '無障礙廁所'), ('water_dispenser', '飲水機'), ('shower', '沖洗設施'), ('locker', '置物櫃'), ('parking', '停車場'), ('life_vest_rental', '救生衣租借處'), ('nursing_room', '哺乳室')], max_length=40)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='ocean_station.station')),
            ],
        ),
        migrations.CreateModel(
            name='StationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=ocean_station.models.station_photo_upload_to)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_display', models.BooleanField(default=True)),
                ('is_cover_image', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ocean_station.stationalbum')),
            ],
        ),
        migrations.CreateModel(
            name='StationAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='ocean_station.station')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stationservice',
            constraint=models.UniqueConstraint(fields=('station', 'service'), name='unique_station_service'),
        ),
        migrations.AddConstraint(
            model_name='stationphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_cover_image', True)), fields=('album',), name='unique_album_cover_image'),
        ),
    ]
