# Generated by Django 4.2.6 on 2026-02-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='en_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
