# Generated by Django 4.2.6 on 2026-02-07 11:39

from django.db import migrations, models
from django.db.models import Q


def fill_station_en_name(apps, schema_editor):
    Station = apps.get_model("ocean_station", "Station")
    for station in Station.objects.filter(Q(en_name__isnull=True) | Q(en_name="")):
        station.en_name = f"station-{station.id}"
        station.save(update_fields=["en_name"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_station', '0002_alter_station_en_name'),
    ]

    operations = [
        migrations.RunPython(fill_station_en_name, noop_reverse),
        migrations.AlterField(
            model_name='station',
            name='en_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
