# Generated by Django 4.2.6 on 2026-02-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocean_station', '0003_fill_station_en_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='en_name',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
