# Generated by Django 4.2.6 on 2026-02-07 13:10

from django.db import migrations, models
import django.db.models.deletion
import ocean_station.models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_unit_landline_phone'),
        ('ocean_station', '0004_alter_station_en_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度'),
        ),
        migrations.AddField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='經度'),
        ),
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='station',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='別名'),
        ),
        migrations.AlterField(
            model_name='station',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='station',
            name='en_name',
            field=models.SlugField(max_length=100, unique=True, verbose_name='英文代稱'),
        ),
        migrations.AlterField(
            model_name='station',
            name='exhibit_plan',
            field=models.TextField(blank=True, null=True, verbose_name='展示規劃'),
        ),
        migrations.AlterField(
            model_name='station',
            name='geo_features',
            field=models.TextField(blank=True, null=True, verbose_name='地理特色'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=100, verbose_name='驛站名稱'),
        ),
        migrations.AlterField(
            model_name='station',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stations', to='organization.unit', verbose_name='承辦單位'),
        ),
        migrations.AlterField(
            model_name='station',
            name='overview',
            field=models.TextField(blank=True, null=True, verbose_name='簡介'),
        ),
        migrations.AlterField(
            model_name='station',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='聯絡電話'),
        ),
        migrations.AlterField(
            model_name='station',
            name='region',
            field=models.CharField(choices=[('north', '北部'), ('central', '中部'), ('south', '南部'), ('east', '東部')], max_length=20, verbose_name='區域'),
        ),
        migrations.AlterField(
            model_name='station',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='stationalbum',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='stationalbum',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='相簿描述'),
        ),
        migrations.AlterField(
            model_name='stationalbum',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='ocean_station.station', verbose_name='驛站'),
        ),
        migrations.AlterField(
            model_name='stationalbum',
            name='title',
            field=models.CharField(max_length=120, verbose_name='相簿名稱'),
        ),
        migrations.AlterField(
            model_name='stationattraction',
            name='name',
            field=models.CharField(max_length=120, verbose_name='周邊景點'),
        ),
        migrations.AlterField(
            model_name='stationattraction',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='ocean_station.station', verbose_name='驛站'),
        ),
        migrations.AlterField(
            model_name='stationphoto',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='ocean_station.stationalbum', verbose_name='相簿'),
        ),
        migrations.AlterField(
            model_name='stationphoto',
            name='caption',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='說明'),
        ),
        migrations.AlterField(
            model_name='stationphoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='stationphoto',
            name='image',
            field=models.ImageField(upload_to=ocean_station.models.station_photo_upload_to, verbose_name='圖片'),
        ),
        migrations.AlterField(
            model_name='stationphoto',
            name='is_cover_image',
            field=models.BooleanField(default=False, verbose_name='是否為封面'),
        ),
        migrations.AlterField(
            model_name='stationphoto',
            name='is_display',
            field=models.BooleanField(default=True, verbose_name='是否顯示'),
        ),
        migrations.AlterField(
            model_name='stationphoto',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='stationservice',
            name='service',
            field=models.CharField(choices=[('accessible_toilet', '無障礙廁所'), ('water_dispenser', '飲水機'), ('shower', '沖洗設施'), ('locker', '置物櫃'), ('parking', '停車場'), ('life_vest_rental', '救生衣租借處'), ('nursing_room', '哺乳室')], max_length=40, verbose_name='服務功能'),
        ),
        migrations.AlterField(
            model_name='stationservice',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='ocean_station.station', verbose_name='驛站'),
        ),
    ]
