# Generated by Django 4.2.6 on 2026-01-20 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coast_guard_mart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('accessory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_accessory_to', to='coast_guard_mart.product')),
                ('main_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessory_relations', to='coast_guard_mart.product')),
            ],
            options={
                'verbose_name': '附屬產品設定',
                'unique_together': {('main_product', 'accessory_item')},
            },
        ),
    ]
