# Generated by Django 4.2.6 on 2026-01-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coast_guard_mart', '0002_productaccessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_display',
            field=models.BooleanField(default=True),
        ),
    ]
