# Generated by Django 4.2.6 on 2026-01-20 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coast_guard_mart', '0003_category_is_public_product_is_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_number', models.CharField(max_length=10, unique=True, verbose_name='身分證字號')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('is_claimed', models.BooleanField(default=False, verbose_name='是否已領取卡片')),
                ('claimed_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whitelist_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '白名單成員',
                'verbose_name_plural': '白名單管理',
            },
        ),
        migrations.CreateModel(
            name='MemberCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.IntegerField(help_text='例如：2026', verbose_name='年度')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10, verbose_name='初始額度')),
                ('balance', models.DecimalField(decimal_places=2, default=3000.0, max_digits=10, verbose_name='剩餘額度')),
                ('start_date', models.DateTimeField(verbose_name='開始使用日期')),
                ('end_date', models.DateTimeField(verbose_name='到期日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '會員點數卡',
                'verbose_name_plural': '會員點數卡',
                'ordering': ['-fiscal_year'],
                'unique_together': {('user', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='消費金額')),
                ('order_id', models.CharField(max_length=100, verbose_name='關聯訂單編號')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='coast_guard_mart.membercredit')),
            ],
        ),
    ]
