# Generated by Django 4.2.6 on 2026-01-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coast_guard_mart', '0004_whitelistmember_membercredit_credittransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credittransaction',
            options={'ordering': ['-timestamp'], 'verbose_name': '消費紀錄', 'verbose_name_plural': '消費紀錄'},
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='取消時間'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='status',
            field=models.CharField(choices=[('PREPARING', '備貨中'), ('COMPLETED', '已完成'), ('CANCELLED', '已取消')], db_index=True, default='PREPARING', max_length=20, verbose_name='訂單狀態'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最後更新時間'),
        ),
        migrations.AddField(
            model_name='credittransaction',
            name='user_remark',
            field=models.TextField(blank=True, null=True, verbose_name='使用者備註'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='description',
            field=models.TextField(blank=True, verbose_name='訂單明細內容'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='order_id',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='關聯訂單編號'),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='交易時間'),
        ),
    ]
