# Generated by Django 4.2.6 on 2026-01-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_unit_en_name'),
        ('coast_guard_mart', '0007_remove_productvariant_price_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelistmember',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='organization.unit', verbose_name='服務單位'),
            preserve_default=False,
        ),
    ]
