# Generated by Django 4.2.6 on 2023-11-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_mobilestorageequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilestorageequipment',
            name='storage_unit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'KB'), (2, 'MB'), (3, 'GB'), (4, 'TB')], default=3, null=True),
        ),
    ]
