# Generated by Django 4.2.6 on 2023-11-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_alter_mobilestorageequipment_storage_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilestorageequipment',
            name='storage_unit',
            field=models.PositiveSmallIntegerField(choices=[(1, 'KB'), (2, 'MB'), (3, 'GB'), (4, 'TB')], null=True),
        ),
    ]
