# Generated by Django 4.2.6 on 2023-11-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_alter_mobilestorageequipment_storage_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilestorageequipment',
            name='model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mobilestorageequipment',
            name='brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mobilestorageequipment',
            name='manage_unit',
            field=models.PositiveIntegerField(choices=[(804012, 'CIE Squad'), (704310, 'First Patrol Station'), (704320, 'Second Patrol Station')], default=804012),
        ),
        migrations.AlterField(
            model_name='mobilestorageequipment',
            name='serial_number',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='mobilestorageequipment',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(5000, 'Other'), (1001, 'Optical Drive'), (1002, 'Digital Audio Recorder'), (1003, 'External Floppy Disk Drive'), (1004, 'External Burner'), (1005, 'Digital Camera'), (1006, 'Wireless Barcode Scanner'), (1007, 'Card Reader'), (1008, 'Driving Recorder'), (2001, 'Thumb Drive'), (2002, 'External Hard Disk Drive'), (2003, 'Memory Card')], default=5000),
        ),
    ]
