# Generated by Django 4.2.6 on 2023-12-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_alter_mobilestorageequipment_manage_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=10)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Smart Phone'), (2, 'Smart Watch')], default=0)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileDeviceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_unit', models.PositiveIntegerField(choices=[(804012, 'CIE Squad'), (704310, 'First Patrol Station'), (704320, 'Second Patrol Station'), (704010, 'XuCuoLiao Inspection Office'), (704020, 'Mailiao Harbor Inspection Office'), (704030, 'WenGang Inspection Office'), (704040, 'WuTiaoGang Fishing Harbor Inspection Office'), (704050, 'TaiXi Fishing Harbor Inspection Office'), (704060, 'SanTiaoLu Fishing Harbor Inspection Office'), (704070, 'BoZiLiao Fishing Harbor Inspection Office'), (704080, 'JinHu Fishing Harbor Inspection Office'), (704090, 'TaiZiVillage Fishing Harbor Inspection Office'), (704110, 'XiaHuKou Inspection Office'), (704210, 'FuLai Fishing Harbor Inspection Office'), (704220, 'XingCuo Fishing Harbor Inspection Office'), (704230, 'WenGang Fishing Harbor Inspection Office'), (704240, 'DongShi Fishing Harbor Inspection Office'), (704250, 'WangLiau Fishing Harbor Inspection Office'), (704260, 'BaiShuiHu Fishing Harbor Inspection Office'), (704270, 'BuDai Fishing Harbor Inspection Office'), (704280, 'BuDai Port Inspection Office'), (704290, 'HauMeiVillage Fishing Harbor Inspection Office')], default=804012)),
                ('manager', models.CharField(max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
