# Generated by Django 4.2.6 on 2023-12-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_mobiledevice_mobiledevicelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiledevice',
            name='owner_commission',
            field=models.CharField(default='NoN', max_length=4),
        ),
    ]
