# Generated by Django 4.2.6 on 2023-12-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_alter_mobiledevice_owner_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobiledevice',
            old_name='brand',
            new_name='SP_brand',
        ),
        migrations.RenameField(
            model_name='mobiledevice',
            old_name='model',
            new_name='SP_model',
        ),
        migrations.RemoveField(
            model_name='mobiledevice',
            name='type',
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='SW_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mobiledevice',
            name='SW_model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mobiledevice',
            name='owner_commission',
            field=models.PositiveIntegerField(choices=[(5140302, 'Non Set'), (1329999161, 'General'), (1329999160, 'Lieutenant General'), (1329999159, 'Major General'), (1329999157, 'Colonel'), (1329999156, 'Lieutenant Colonel'), (1329999155, 'Major'), (1329999154, 'Captain'), (1329999153, 'First Lieutenant'), (20294, 'Second Lieutenant'), (1330785593, 'Sergeant Major'), (1330785592, 'First Sergeant'), (1330785591, 'Sergeant First Class'), (1330785590, 'Staff Sergeant'), (1330785589, 'Sergeant'), (1330785588, 'Corporal'), (1330785587, 'Private First Class'), (1330785586, 'Private E2'), (1330785585, 'Private')], default=5140302),
        ),
        migrations.AlterField(
            model_name='mobiledevicelist',
            name='manage_unit',
            field=models.PositiveIntegerField(choices=[(804012, 'CIE Squad'), (704310, 'First Patrol Station'), (704320, 'Second Patrol Station'), (704010, 'XuCuoLiao Inspection Office'), (704020, 'Mailiao Harbor Inspection Office'), (704030, 'WenGang Inspection Office'), (704040, 'WuTiaoGang Fishing Harbor Inspection Office'), (704050, 'TaiXi Fishing Harbor Inspection Office'), (704060, 'SanTiaoLu Fishing Harbor Inspection Office'), (704070, 'BoZiLiao Fishing Harbor Inspection Office'), (704080, 'JinHu Fishing Harbor Inspection Office'), (704090, 'TaiZiVillage Fishing Harbor Inspection Office'), (704110, 'XiaHuKou Inspection Office'), (704210, 'FuLai Fishing Harbor Inspection Office'), (704220, 'XingCuo Fishing Harbor Inspection Office'), (704230, 'WenGang Fishing Harbor Inspection Office'), (704240, 'DongShi Fishing Harbor Inspection Office'), (704250, 'WangLiau Fishing Harbor Inspection Office'), (704260, 'BaiShuiHu Fishing Harbor Inspection Office'), (704270, 'BuDai Fishing Port Inspection Office'), (704280, 'BuDai Port Inspection Office'), (704290, 'HauMeiVillage Fishing Harbor Inspection Office')], default=804012),
        ),
        migrations.AlterField(
            model_name='mobilestorageequipment',
            name='manage_unit',
            field=models.PositiveIntegerField(choices=[(804012, 'CIE Squad'), (704310, 'First Patrol Station'), (704320, 'Second Patrol Station'), (704010, 'XuCuoLiao Inspection Office'), (704020, 'Mailiao Harbor Inspection Office'), (704030, 'WenGang Inspection Office'), (704040, 'WuTiaoGang Fishing Harbor Inspection Office'), (704050, 'TaiXi Fishing Harbor Inspection Office'), (704060, 'SanTiaoLu Fishing Harbor Inspection Office'), (704070, 'BoZiLiao Fishing Harbor Inspection Office'), (704080, 'JinHu Fishing Harbor Inspection Office'), (704090, 'TaiZiVillage Fishing Harbor Inspection Office'), (704110, 'XiaHuKou Inspection Office'), (704210, 'FuLai Fishing Harbor Inspection Office'), (704220, 'XingCuo Fishing Harbor Inspection Office'), (704230, 'WenGang Fishing Harbor Inspection Office'), (704240, 'DongShi Fishing Harbor Inspection Office'), (704250, 'WangLiau Fishing Harbor Inspection Office'), (704260, 'BaiShuiHu Fishing Harbor Inspection Office'), (704270, 'BuDai Fishing Port Inspection Office'), (704280, 'BuDai Port Inspection Office'), (704290, 'HauMeiVillage Fishing Harbor Inspection Office')], default=804012),
        ),
    ]
