# Generated by Django 4.2.6 on 2023-12-17 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('business', '0015_alter_mobiledevice_owner_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilestorageequipment',
            name='manage_unit',
        ),
        migrations.AddField(
            model_name='mobilestorageequipment',
            name='manage_unit_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='mobilestorageequipment',
            name='manage_unit_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
