# Generated by Django 4.2.6 on 2023-12-17 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_mobiledevice_owner_unit_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobiledevice',
            name='owner_unit',
        ),
    ]
