# Generated by Django 4.2.6 on 2023-12-31 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_remove_mobiledevice_owner_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategorydetail',
            name='sub_category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
        migrations.DeleteModel(
            name='SubcategoryDetail',
        ),
    ]
