# Generated by Django 4.2.6 on 2024-03-03 09:12

import business.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_oceanstation_cover_photo_alter_oceanstation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oceanstation',
            name='cover_photo',
            field=models.ImageField(null=True, upload_to=business.models.OceanStation._image_upload_path),
        ),
    ]
