# Generated by Django 4.2.6 on 2025-12-26 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_alter_oceanstation_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateapplication',
            name='applicant_unit_content_type',
        ),
        migrations.RemoveField(
            model_name='mobiledevice',
            name='owner_unit_content_type',
        ),
        migrations.DeleteModel(
            name='MobileDeviceList',
        ),
        migrations.RemoveField(
            model_name='mobilestorageequipment',
            name='manage_unit_content_type',
        ),
        migrations.DeleteModel(
            name='CertificateApplication',
        ),
        migrations.DeleteModel(
            name='MobileDevice',
        ),
        migrations.DeleteModel(
            name='MobileStorageEquipment',
        ),
    ]
