# Generated by Django 4.2.6 on 2024-06-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_alter_oceanstation_cover_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateapplication',
            name='applicant_unit_content_type',
        ),
        migrations.RemoveField(
            model_name='mobiledevice',
            name='owner_unit_content_type',
        ),
        migrations.DeleteModel(
            name='MobileDeviceList',
        ),
        migrations.RemoveField(
            model_name='mobilestorageequipment',
            name='manage_unit_content_type',
        ),
        migrations.AddField(
            model_name='oceanstation',
            name='oid',
            field=models.CharField(default='cgaoid0', max_length=150, unique=True),
        ),
        migrations.DeleteModel(
            name='CertificateApplication',
        ),
        migrations.DeleteModel(
            name='MobileDevice',
        ),
        migrations.DeleteModel(
            name='MobileStorageEquipment',
        ),
    ]
