# Generated by Django 4.2.6 on 2024-06-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_remove_certificateapplication_applicant_unit_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oceanstation',
            name='oid',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
