# Generated by Django 4.2.6 on 2026-01-27 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='球館名稱')),
                ('address', models.TextField(verbose_name='地址')),
                ('phone', models.CharField(max_length=20, verbose_name='聯絡電話')),
            ],
        ),
        migrations.CreateModel(
            name='MemberWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='可用點數')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_wallets', to='badminton_court_management.gym')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'gym')},
            },
        ),
        migrations.CreateModel(
            name='PointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='變動點數')),
                ('reason', models.CharField(max_length=100, verbose_name='變動原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='badminton_court_management.memberwallet')),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='場地編號 (如: A場)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否開放')),
                ('price_per_hour', models.IntegerField(default=500, verbose_name='每小時點數')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='badminton_court_management.gym')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='預約日期')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='結束時間')),
                ('total_points', models.IntegerField(verbose_name='扣除點數')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('confirmed', '預約成功'), ('cancelled', '已取消')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badminton_court_management.court')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('court', 'booking_date', 'start_time')},
            },
        ),
    ]
