# Generated by Django 4.2.6 on 2026-01-28 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badminton_court_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50, unique=True, verbose_name='訂單編號')),
                ('amount', models.IntegerField(verbose_name='實際支付金額')),
                ('points', models.IntegerField(verbose_name='實際獲得點數')),
                ('status', models.CharField(choices=[('pending', '待付款'), ('processing', '支付中'), ('success', '儲值成功'), ('failed', '儲值失敗'), ('cancelled', '已取消')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='完成支付時間')),
            ],
        ),
        migrations.CreateModel(
            name='TopupPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='方案名稱')),
                ('amount', models.PositiveIntegerField(verbose_name='支付金額 (TWD)')),
                ('points', models.PositiveIntegerField(verbose_name='獲得點數')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='推薦方案')),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_plans', to='badminton_court_management.gym')),
            ],
        ),
        migrations.CreateModel(
            name='TopupOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=15, verbose_name='原狀態')),
                ('to_status', models.CharField(max_length=15, verbose_name='新狀態')),
                ('operator', models.CharField(default='System', max_length=50, verbose_name='操作者')),
                ('remark', models.TextField(blank=True, verbose_name='變動備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='紀錄時間')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='badminton_court_management.topuporder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='topuporder',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='badminton_court_management.topupplan'),
        ),
        migrations.AddField(
            model_name='topuporder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topuporder',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badminton_court_management.memberwallet'),
        ),
    ]
