# Generated by Django 4.2.6 on 2026-02-06 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('badminton_court_management', '0005_topupplan_deactivated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gymstaff',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_roles', to='badminton_court_management.gym'),
        ),
        migrations.AlterField(
            model_name='gymstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gym_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberwallet',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_wallets', to='badminton_court_management.gym'),
        ),
        migrations.AlterField(
            model_name='memberwallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pointlog',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='badminton_court_management.memberwallet'),
        ),
        migrations.AlterField(
            model_name='topuporder',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='badminton_court_management.topupplan'),
        ),
        migrations.AlterField(
            model_name='topuporder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topuporder',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='badminton_court_management.memberwallet'),
        ),
        migrations.AlterField(
            model_name='topuporderlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='badminton_court_management.topuporder'),
        ),
        migrations.AlterField(
            model_name='topupplan',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topup_plans', to='badminton_court_management.gym'),
        ),
    ]
