# Generated by Django 4.2.6 on 2023-12-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.PositiveSmallIntegerField(choices=[(1, 'Personal'), (1, 'Agency'), (1, 'Server')], default=1)),
                ('applicant_name', models.CharField(max_length=10)),
                ('applicant_contact_number', models.CharField(max_length=10)),
                ('applicant_unit', models.PositiveSmallIntegerField(choices=[(803000, 'CPC3'), (804000, 'CPC4')], default=804000)),
                ('applicant_address', models.CharField(max_length=255)),
                ('custodian_name', models.CharField(max_length=10)),
                ('custodian_ID_number', models.CharField(max_length=10)),
                ('custodian_contact_number', models.CharField(max_length=10)),
                ('custodian_email', models.CharField(max_length=255)),
                ('custodian_classification', models.PositiveSmallIntegerField(choices=[(1, 'Unit'), (2, 'Voluntary Military'), (3, 'Obligatory Military'), (4, 'CivilServant'), (5, 'Police'), (6, 'Outsource')], default=1)),
                ('storage', models.PositiveSmallIntegerField(choices=[(1, 'IC Card'), (2, 'Magnetic Disk')], default=1)),
                ('process', models.PositiveSmallIntegerField(choices=[(1, 'Apply'), (2, 'Undo'), (3, 'Reissue'), (4, 'Report a Loss'), (5, 'Recover'), (6, 'Reschedule')], default=1)),
                ('use_for', models.PositiveSmallIntegerField(choices=[(1, 'Duty'), (2, 'Business')], default=2)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
