# Generated by Django 4.2.6 on 2023-12-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateapplication',
            name='custodian_commission',
            field=models.PositiveIntegerField(choices=[(5140302, 'Non Set'), (1329999161, 'General'), (1329999160, 'Lieutenant General'), (1329999159, 'Major General'), (1329999157, 'Colonel'), (1329999156, 'Lieutenant Colonel'), (1329999155, 'Major'), (1329999154, 'Captain'), (1329999153, 'First Lieutenant'), (20294, 'Second Lieutenant'), (1330785593, 'Sergeant Major'), (1330785592, 'First Sergeant'), (1330785591, 'Sergeant First Class'), (1330785590, 'Staff Sergeant'), (1330785589, 'Sergeant'), (1330785588, 'Corporal'), (1330785587, 'Private First Class'), (1330785586, 'Private E2'), (1330785585, 'Private')], default=5140302),
        ),
    ]
