# Generated by Django 4.2.6 on 2023-12-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0002_certificateapplication_custodian_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateapplication',
            name='applicant_unit',
            field=models.PositiveSmallIntegerField(choices=[(0, '尚未設定'), (804000, '第四岸巡隊'), (804930, '勤務分隊'), (804012, '通資小隊'), (704310, '第一機動巡邏站'), (704320, '第二機動巡邏站'), (704010, '許厝寮安檢所'), (704020, '麥寮工業港安檢所'), (704030, '蚊港安檢所'), (704040, '五條港漁港安檢所'), (704050, '台西漁港安檢所'), (704060, '三條崙漁港安檢所'), (704070, '箔子寮漁港安檢所'), (704080, '金湖漁港安檢所'), (704090, '台子村漁港安檢所'), (704110, '下湖口安檢所'), (704210, '副瀨漁港安檢所'), (704220, '型厝漁港安檢所'), (704230, '塭港漁港安檢所'), (704233, '塭港執檢站'), (704240, '東石漁港安檢所'), (704250, '網寮漁港安檢所'), (704260, '白水湖漁港安檢所'), (704270, '布袋漁港安檢所'), (704280, '布袋商港安檢所'), (704290, '好美里漁港安檢所')], default=804000),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='usage',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Personal'), (2, 'Agency'), (3, 'Server')], default=1),
        ),
        migrations.AlterField(
            model_name='certificateapplication',
            name='use_for',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Duty'), (2, 'Business'), (3, 'System Using'), (4, 'Register'), (5, 'New Position'), (6, 'Transfer Position'), (7, 'Retirement'), (8, 'Change Soft Certificate'), (9, 'Broken Reapply')], default=2),
        ),
    ]
