# Generated by Django 4.2.6 on 2024-01-15 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0004_category_order_record_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificateApplication',
        ),
    ]
