# Generated by Django 4.2.6 on 2024-01-16 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('market_place', '0005_delete_certificateapplication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-created_time']},
        ),
        migrations.AddField(
            model_name='record',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='record',
            name='log_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin.logentry'),
        ),
        migrations.AddField(
            model_name='record',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='content',
            field=models.TextField(),
        ),
    ]
