# Generated by Django 4.2.6 on 2024-01-16 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0006_alter_record_options_record_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='log_entry',
        ),
    ]
