# Generated by Django 4.2.6 on 2024-01-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_place', '0007_remove_record_log_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
