# Generated by Django 4.2.6 on 2026-02-11 02:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('security_scanner', '0002_scanresult_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanresult',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
