# Generated by Django 4.2.6 on 2026-01-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=6)),
                ('maximum_participant_number', models.PositiveSmallIntegerField()),
                ('starting_time', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('creator', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=8)),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField()),
            ],
        ),
    ]
